name: qr
version: 1.3.0-dev
description: >-
  A QR code generation library for Dart and Flutter.
  Supports QR code version 1 through 40, error correction and redundancy.
homepage: https://github.com/kevmoo/qr.dart/

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  meta: ^1.1.0 # dart.dev

dev_dependencies:
  build_runner: ^1.1.2 # dart.dev
  build_web_compilers: ^2.9.0 # dart.dev / google - https://github.com/dart-lang/build
  pedantic: ^1.0.0 # dart.dev
  stream_transform: ^1.0.0 # google
  test: ^1.5.0 # dart.dev
